services:
  mercuryou:
    image: node:23-slim
    container_name: mercuryou
    restart: unless-stopped
    working_dir: /home/node
    volumes:
      - ./:/home/node/:cached
    # must be build locally, digitalOcean low end machine cant handle that
    command: bash -c "npm install && npm run start"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercuryou.rule=Host(`mercuryou.txto.com.br`)"
      - "traefik.http.routers.mercuryou.entrypoints=websecure"
      - "traefik.http.routers.mercuryou.tls.certresolver=myresolver"
      - "traefik.http.services.mercuryou.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true
